### PR TITLE
Pass context object to preprocessors

### PR DESCRIPTION
**Pull request by jcmfernandes**
ATM, if one wants to access a variable with limited scope inside a
preprocessor, the only way to do that is by creating anonymous schemas
on-the-fly and take advantage from the fact that ruby blocks act as
closures. Example:

```ruby
def create_schema(offset)
  Conformist.new do
    column :numeric_value do |value|
      offset + value.to_i
    end
  end
end
```

This change allows developers to pass a context object (typically an hash, but
I'm not enforcing it) to the preprocessors, without the need to continuously
create anonymous schemas. Example:

```ruby
SCHEMA =
  Conformist.new do
    column :numeric_value do |value, context|
      context[:offset].to_i + value.to_i
    end
  end

SCHEMA.conform(something, context: {offset: 5})
```

### CODE REVIEW

**Comment by jcmfernandes** [comment]
I'll update the README if this change is interesting.

**Comment by jcmfernandes** [comment]
@tatey I just noticed that you proposed this in https://github.com/tatey/conformist/pull/5#issuecomment-11374713 😸 am I missing something here?

**Comment by tatey** [comment]
This looks great @jcmfernandes :+1:

> I'll update the README if this change is interesting.

Yes, please. Leave the CHANGELOG though. I'll update that when I cut the release.

**Review by tatey — APPROVED** [review]

**Comment by jcmfernandes** [comment]
@tatey I forcefully-pushed to the branch, as I did a small change to the existing commit. Essentially, we should check the arity of the preprocessor block to avoid breaking things for those who are using lambdas or methods as preprocessors.

I'll now change the README 😉 thanks for the quick reply!

**Comment by tatey** [comment]
> I forcefully-pushed to the branch, as I did a small change to the existing commit. Essentially, we should check the arity of the preprocessor block to avoid breaking things for those who are using lambdas or methods as preprocessors.

Cool.

> I'll now update the README 😉 thanks for the quick reply!

Do you need a hand, or would you prefer me to do this?

**Comment by jcmfernandes** [comment]
Hey @tatey sorry for the delay, I took a long weekend off.

I updated the README file with a simple use-case. Let me know if you feel like that should be improved, or feel more than free to change it yourself.

**Comment by tatey** [comment]
No need to apologise at all. I understand this is a volunteer effort and I'm grateful for the patch 😄 

I've [cut a new release](https://rubygems.org/gems/conformist/versions/0.2.5) and [updated the changelog](https://github.com/tatey/conformist/blob/06e3f2e31aaa47023a87aa9d6e03132d0fb4ebf7/CHANGELOG.md).

Thanks.

**Comment by jcmfernandes** [comment]
Thank you! 😺 🎉

**Pull request merged**
